<a href="https://colab.research.google.com/github/nidjaj/machine-learning-/blob/master/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [0]:
a=np.array([[1,4],[2,6]])

In [4]:
a

array([[1, 4],
       [2, 6]])

In [0]:
x = np.array([[1, 2], [3, 4]]) 
y = np.array([[5, 6], [7, 8]])

In [0]:
v = np.array([9, 10]) 
w = np.array([11, 12]) 

In [7]:
print(np.dot(v, w), "\n") 

219 



In [10]:
np.linspace(1., 4.,  6)

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

linspace() will create arrays with a specified number of elements, and spaced equally between the specified beginning and end values. 

indices() will create a set of arrays (stacked as a one-higher dimensioned array), one per dimension with each representing variation in that dimension. An example illustrates much better than a verbal description:

In [11]:
np.indices((3,3))

array([[[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]],

       [[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]])

In [12]:
np.indices((3,2))

array([[[0, 0],
        [1, 1],
        [2, 2]],

       [[0, 1],
        [0, 1],
        [0, 1]]])

In [0]:
data = u"123456789\n   4  7 9\n   4567 9"

In [0]:
from io import StringIO

In [16]:
np.genfromtxt(StringIO(data), delimiter=(4, 3, 2))

array([[1234.,  567.,   89.],
       [   4.,    7.,    9.],
       [   4.,  567.,    9.]])

In [0]:
data = u"123456789\n 4  7 9\n4567 9"

In [18]:
np.genfromtxt(StringIO(data), delimiter=(4, 3, 2))

array([[1.234e+03, 5.670e+02, 8.900e+01],
       [4.000e+00,       nan,       nan],
       [4.567e+03, 9.000e+00,       nan]])

In [0]:
x= np.arange(10)

In [24]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
x.shape = (2,5)

In [26]:
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [0]:
y = np.arange(35).reshape(5,7)

In [28]:
y

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [29]:
y[1:5:2,::3]

array([[ 7, 10, 13],
       [21, 24, 27]])

In [0]:
x = np.arange(10,1,-1)

In [31]:
x

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [32]:
x[np.array([3, 3, 1, 8])]

array([7, 7, 9, 2])

The index array consisting of the values 3, 3, 1 and 8 correspondingly create an array of length 4 (same as the index array) where each index is replaced by the value the index array has in the array being indexed.

Negative values are permitted and work as they do with single indices or slices:

>>>
>>> x[np.array([3,3,-3,8])]
array([7, 7, 4, 2])
It is an error to have index values out of bounds:

>>>
>>> x[np.array([3, 3, 20, 8])]
<type 'exceptions.IndexError'>: index 20 out of bounds 0<=index<9
Generally speaking, what is returned when index arrays are used is an array with the same shape as the index array, but with the type and values of the array being indexed. As an example, we can use a multidimensional index array instead:

>>>
>>> x[np.array([[1,1],[2,3]])]
array([[9, 9],
       [8, 7]])

In [0]:
 z = np.arange(81).reshape(3,3,3,3)

In [35]:
z

array([[[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]],


       [[[27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]],

        [[36, 37, 38],
         [39, 40, 41],
         [42, 43, 44]],

        [[45, 46, 47],
         [48, 49, 50],
         [51, 52, 53]]],


       [[[54, 55, 56],
         [57, 58, 59],
         [60, 61, 62]],

        [[63, 64, 65],
         [66, 67, 68],
         [69, 70, 71]],

        [[72, 73, 74],
         [75, 76, 77],
         [78, 79, 80]]]])

In [36]:
 z[1,...,2]

array([[29, 32, 35],
       [38, 41, 44],
       [47, 50, 53]])

In [37]:
z[1,:,:,2]

array([[29, 32, 35],
       [38, 41, 44],
       [47, 50, 53]])

In [0]:
indices = (1,1,1,1)

In [39]:
z[indices]

40

In [0]:
indices = (1,1,1,slice(0,2)) # same as [1,1,1,0:2]

In [41]:
z[indices]

array([39, 40])

In [0]:
indices = (1, Ellipsis, 1) # same as [1,...,1]

In [43]:
z[indices]

array([[28, 31, 34],
       [37, 40, 43],
       [46, 49, 52]])